version: '3'
services:

  # NodeJS app
  web:
    build: ./app
    volumes:
      - "./app:/src/app"
    ports:
      - "3030:3000"
    links:
      - db:redis
    networks:
      - webnet
    environment: 
      - REDIS_HOST=redis
    command: npm start
  
  # nging proxy
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - /www/public
    links:
      - web:web

  # Redis store
  db:
    hostname: redis
    image: redis
    ports:
      - "6379"
    networks:
      - webnet

  # Database

networks:
  webnet: