version: '3.5'
services:
  #### Nginx proxy
  nginx:
    restart: always
    build: ./nginx-example
    ports:
      - 80:8181
      #- 8443:443
    volumes:
      - ./nginx-example/nginx:/etc/nginx
      - ./nginx-example/www:/usr/share/nginx/html
    networks:
      - frontend
  
  #### Python Web App
  web:
    build: ./web
    ports:
      - 9000:3000
    depends_on: 
      - db
    links:
      - db:redis
    networks:
      - frontend
      - backend
    environment: 
      - REDIS_HOST=redis
      - PORT=3000
      - FLASK_ENV=production
  
  #### NodeJS app
  app:
    build: ./app
    #image: jsapps/nodejs-app:latest
    command: node bin/www
    volumes:
      - ./app:/src/app
    ports:
      - 9001:9000
    depends_on: 
      - db
    links:
      - db:redis
    networks:
      - frontend
      - backend
    environment: 
      - REDIS_HOST=redis
      - DEBUG=connect:*
      - PORT=9000
  
    
  #### Redis store
  db:
    hostname: redis
    image: redis
    ports:
      - 6379
    networks:
      - backend

# Networks
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge