version: "3"
services:
  #### Nginx proxy
  nginx:
    restart: always
    build: ./nginx-example
    ports:
      - 8181:8181
      #- 8443:443
    volumes:
      - ./nginx-example/nginx:/etc/nginx
      - ./nginx-example/www:/usr/share/nginx/html
    networks:
      - webnet
  
  #### Python Web App
  web:
    build: ./web
    restart: always
    ports:
      - 9000:3000
    depends_on: 
      - db
    links:
      - db:redis
    networks:
      - webnet
      - backend
    environment: 
      - REDIS_HOST=redis
      #- REDIS_PORT=32770
      #- PORT=3000
      - FLASK_ENV=production
  
  #### NodeJS app
  app:
    restart: always
    build: ./app
    #image: jsapps/nodejs-app:latest
    command: node bin/www
    ports:
      - 9001:9000
    depends_on: 
      - db
    links:
      - db:redis
    networks:
      - webnet
    environment: 
      - REDIS_HOST=redis
      - DEBUG=connect:*
      - PORT=9000
  
    
  #### Redis store
  db:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

# Networks
networks:
  webnet:
  frontend:
    driver: bridge
  backend:
    driver: bridge