version: '3'
services:
  #### Nginx cache
  proxy:
    restart: always
    image: bitnami/nginx:latest 
    #build: ./nginx-proxy
    volumes:
      - ./nginx-proxy/public:/app
      #- ./my_vhost.conf:/bitnami/nginx/conf/vhosts/my_vhost.conf:ro

  #### NodeJS app
  web:
    build: ./app
    #image: jsapps/nodejs-app:latest
    command: node bin/www
    volumes:
      - "./app:/src/app"
    ports:
      - 3000
    depends_on: 
      - db
    links:
      - db:redis
    networks:
      - webnet
    environment: 
      - REDIS_HOST=redis
      #- DEBUG=*
  
    
  #### Redis store
  db:
    hostname: redis
    image: redis
    ports:
      - 6379
    networks:
      - webnet

  # Database


networks:
  webnet: