version: '3'
services:
  
  #### Python Web App
  web:
    restart: always
    build: ./web
    ports:
      - 9000:3000
    volumes:
      - /www/public
    networks:
      - webnet
  
  #### Nginx proxy
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
      - 8443:443
    volumes:
      - /www/public
      - ./public:/app
    links:
      - web:web
    networks:
      - webnet

  #### NodeJS app
  app:
    build: ./app
    #image: jsapps/nodejs-app:latest
    command: node bin/www
    volumes:
      - ./app:/src/app
    ports:
      - 3000
    depends_on: 
      - db
    links:
      - db:redis
    networks:
      - webnet
    environment: 
      - REDIS_HOST=redis
      - DEBUG=*
  
    
  #### Redis store
  db:
    hostname: redis
    image: redis
    ports:
      - 6379
    networks:
      - webnet

  # Database
networks:
  webnet: