apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cadvisor
    spec:
      containers:
      - image: google/cadvisor:latest
        name: cadvisor
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /rootfs
          name: cadvisor-claim0
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-claim1
        - mountPath: /sys
          name: cadvisor-claim2
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-claim3
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: cadvisor-claim0
        persistentVolumeClaim:
          claimName: cadvisor-claim0
          readOnly: true
          type: DirectoryOrCreate
      - name: cadvisor-claim1
        persistentVolumeClaim:
          claimName: cadvisor-claim1
          type: DirectoryOrCreate
      - name: cadvisor-claim2
        persistentVolumeClaim:
          claimName: cadvisor-claim2
          type: DirectoryOrCreate
      - name: cadvisor-claim3
        persistentVolumeClaim:
          claimName: cadvisor-claim3
          readOnly: true
status: {}
